### ISSUE TITLE
Remove tokio runtime in rust control interface example

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#113]
## Description

Currently, there is tokio and async code used for one read and one writer that needs to be run separately. To remove package dependencies and to keep the example more simple (like other control interface examples), remove the async tokio code and replace it through native os threads with standard library feature.

## Goals

No async or extra tokio runtime in the rust control interface example

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Removes async tokio code from rust control interface example => use native OS threads and reduce usage of third party packages in example
- [x] Changing the user doc about control interface

**Comment by krucod3** [comment]
Seems like all is done here.
