### ISSUE TITLE
Support JSON and YAML as output in ank CLI

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#119]
## Description

Currently the output format of Ankaios CLI is YAML or table format.
For parsing and automation the JSON format as default output would be more suitable.

## Goals

Ankaios CLI shall output its content in JSON format.

### Summary

We shall add options for the output format for all command of the ank CLI.

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by windsource** [comment]
I think providing output in JSON format for automated processing is a good idea. Especially `ank get workloads` only provides a table format without an option for output in a structured format. So an option `-o FORMAT` with FORMAT being either `yaml` or `json` might be useful. However the default format especially for `ank get workloads` should still be table format as this is the easiest one for humans to get a quick overview.

**Comment by krucod3** [comment]
`ank get state` already provides this functionality. If we add a json output to `get workloads` we would have yet another config/output format in Ankaios.

**Comment by windsource** [comment]
@krucod3 you are right, `ank get state` already provides a structured output and for example with:

```shell
❯ ank get state -o json | jq -r '.workloadStates[] | select( .workloadName == "nginx" ) | .executionState'
ExecRunning
```

I can get the state of a workload with the name `nginx`. However I think most Ankaios users will use `ank get workloads` in the first place as it more convenient and then later one tend to use it also for automation in scripts. With supporting the `-o` option also for `ank get workloads` we can just return the `workloadStates` so it should be easy to implement and convenient to use. Then the command above would be:

```shell
❯ ank get workloads -o json | jq -r '.[] | select( .workloadName == "nginx" ) | .executionState'
ExecRunning
```

**Comment by windsource** [comment]
I see that the output of `ank get workloads` is not equal to the `workloadStates` part of `ank get state` as some information like the runtime of the `currentState` are added. In that case we should at least extend the `ank get --help` to indicate, that the user shall use `ank get state` for automation.
