### ISSUE TITLE
Review and consider supplementing tokio with async-std

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#12]
Reported by @krucod3:

## Description

Currently we are using tokio as an asynchronous runtime. The reason was just convenience because of the wide spread usage of the tokio runtime. 
After discussions with Eclipse SDV community during one of the community days, we got some information that tokio is targeted more at the web service use-case and shows some performance issues under certain circumstances (https://zenoh.io/blog/2022-04-14-rust-async-eval/).

Additionally if there is a functional safe Rust compiler, we would also need a functional safe crate ecosystem and the thoughts of Ferrous Systems on the topic were that async-std is far more suitable for certification. 

Even if we are not targeting at ASIL certification for now, it would be better if we are using an asynchronous runtime adopted by the majority in the automotive sector.

## Goals

* Review [async-std](https://docs.rs/async-std/latest/async_std/) and compare it feature-wise with [tokio](https://docs.rs/tokio/latest/tokio/) (https://tokio.rs/). 
* Review in depth the [analysis of ZettaScale](https://zenoh.io/blog/2022-04-14-rust-async-eval/)
* Give a recommendation if we should switch to async-std

## Tasks

tbd.

**Comment by krucod3** [comment]
In the meantime ZettaScale switched to tokio because of the growing community and the recent performance improvements.
With them investing time and effort to switch to tokio for Zenoh it does not make sense that we analyze async-std at the moment.
