### ISSUE TITLE
Handle all Podman states 

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#123]
As found by @maturar, we sometimes return unknown state while stopping a container via Podman because we don't cover all possible Podman states. The Podman documentation is unfortunately very sparse in that regard and only mentions some of the possible states:  ‘created’, ‘exited’, ‘paused’, ‘running’, ‘unknown’ (see https://docs.podman.io/en/latest/markdown/podman-ps.1.html).

In the Podman implementation we can see that there are also other possible states (the marked **bold** are currently mapped to unknown in Ankaios):
* unknown
* created
* **configured**
* **initialized**
* running
* stopped
* **paused**
* exited
* **removing**
* **stopping**
(see https://github.com/containers/podman/blob/main/libpod/define/containerstate.go#L42)

## Current Behavior
When Podman returns one of the marked in bold steps above, Ankaios coverts this to a `unknown`

## Expected Behavior
Ankaios maps properly all execution states

## Steps to Reproduce
Stop Podman workloads and monitor the workload states or observe the traces. 
With the correct timing unknown execution states will be shown by Ankaios

## Final result

The current impact is rather limited as there is are no actions taken depending on the states. This will change soon with the introduction of the dependency management in #48.

To fix the issue it would be enough to map the unhandled Podman states to the currently supported ones, but also according to observations made during the preparations for #48, we would also need a `stopping` state. This will be handled in a separate PR as a subtask of #48.

**Comment by maturar** [comment]
The change requested by this issue depends on the #125 (a subtask of #48). The PR #125 is ready for review.

**Comment by maturar** [comment]
The pull request with the fix has been reviewed and merged into main.
