### ISSUE TITLE
CLI should report state when running or deleting workloads

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#13]
Reported by @krucod3:

## Description

Currently when a workload fails during startup there is only a log message. This is not very informative when using the cli and does not allow proper health management. Additionally deleting workloads should also deliver a result (workload deleted)

## Goals

We should improve the success/error handling of starting workloads s.t.:
* success:
    * cli outputs success or failure
* error:
    * other agents get a workload failed workload state This shall be sent when something during the creation/setup of the Workload fails inside the spawned task.
    * the cli get and outputs the state to the used

We should inform when a workload was deleted.

As mentioned by @windsource, it would be great if we use a create for the CLI output which also supports Windows. The server and the agent are not targeted at Windows, but a user could require to run the CLI on a Windows machine. **We don't need to test the Windows support for now, but we should "keep the door open" for a later support.**

## Tasks

- [ ] Unit tests 
- [ ] System tests
- [ ] User documentation 
- [ ] Design documentation

**Comment by krucod3** [comment]
We had to add some stop handling to the CLI with #100. We should review if we still need the Goodbye messages once this here is implemented.

**Comment by krucod3** [comment]
Maybe we should also add some responses to the `set state`, e.g., accepted or failed.

**Comment by krucod3** [comment]
I'll check the user and design documentation.

**Comment by maturar** [comment]
I am going to review the implementation and I will eventually do the unit tests too (not sure if I can make it before my vacation next week).

**Comment by lingnoi** [comment]
I'll take care for the system tests.
