### ISSUE TITLE
When opening in CodeSpaces, Python error

### ISSUE THREAD

**Issue by koppor** [eclipse-ankaios/ankaios#131]
I press <kbd>,</kbd> do open the development environment in GitHub's Codespaces. The environment starts, put has following error message:

> Invalid python version for workspace folder 'ankaios'. Only python version >= 3.8 supported. Please update to a newer python version or select a valid python environment.

Is python really required? 😋

**Comment by windsource** [comment]
I cannot reproduce that. Python is part of the dev container as we need it to run the system tests with the robot framework. Also we generate the documentation with MkDocs which requires Python as well. 
So when I start a Codespace I do not get that error. @koppor could you provide addtional infos about your workflow?

**Comment by koppor** [comment]
I was with a friend and used his old MacBook Pro and Google Chrome. Tried again on Windows 10 with a Google Chrome. Same result:

![image](https://github.com/eclipse-ankaios/ankaios/assets/1366654/117a8cfb-0fde-49d6-967e-850695eafa76)


OK, Click on "Retry" fixes the issue. Thus a no-issue. Sorry to the noise!
