### ISSUE TITLE
Protocol documentation with confusing message directions

### ISSUE THREAD

**Issue by Rosinski1** [eclipse-ankaios/ankaios#145]
The protocol documentation describes two main messages and their directions:
1. StateChangeRequest: agent/cli -> server
2. ExecutionRequest: server -> agent/cli

## Current Behavior
Description of `StateChangeRequest` is the following: "Messages to the Ankaios server."
Description of `ExecutionRequest` is the following: "Messages to the Ankaios server."

## Expected Behavior
Description of `ExecutionRequest` should be: "Messages to a Ankaios agent."

## Steps to Reproduce
Visit the documentation here: https://eclipse-ankaios.github.io/ankaios/latest/reference/_ankaios.proto/#executionrequest
or here: https://github.com/eclipse-ankaios/ankaios/blob/64378198757947bef9d275af5221f83427c12125/api/proto/ankaios.proto#L56C13-L56C13

## Context (Environment)
-

## Logs
-

## Additional Information
A change in the `ankaios.proto` file of the description from the `ExecutionRequest`-Message at line 56 should be enough.

## Final result
-

**Comment by christoph-hamm** [comment]
Yes, you a right, the description for `ExecutionRequest` is wrong. We are currently making some bigger changes on the `ankaios.proto` file for #13. We will fix the documentation there.

**Comment by krucod3** [comment]
This will be solved by #152.

**Comment by christoph-hamm** [comment]
As #152 has been merged, this is fixed.
