### ISSUE TITLE
Workload health checks interval configurable

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#15]
Reported by @krucod3:

## Description

Currently the workload health checks are done every 1000ms. This behavior shall be configurable by the users of Ankaios. There are in general two ways how this can be configured:
* a general setting per Agent provided via the command line at startup
* a custom setting per Workload provided with the start up config that overwrites the Agent setting.

## Goals

Make the workload health checks more user-friendly

## Tasks

- [ ] Add a command line setting for the Agent that specifies the general health check interval. Use a default of 1000ms as configured now.
- [ ] Add a new config option per workload in the start up config and the system current and start up state. Document that the interval can only be changed on workload start and if a dynamic change during runtime is required, a workload restart is needed (we could also restart only the checker, but this would be too much work with no benefit ;) )

**Comment by windsource** [comment]
As stated in #48 maybe we also need more fine grained health checks than just check that the container is running.

**Comment by krucod3** [comment]
This issue will be handled as part of the bigger story about general configurable health checks #109
