### ISSUE TITLE
reusable workloads not resumed properly

### ISSUE THREAD

**Issue by sboett-dev** [eclipse-ankaios/ankaios#158]
When Ankaios agents find "reusable podman/podman-kube workloads" on startup, resuming always end up in a `ExecSucceeded` state instead of an `ExecRunning` state.

## Current Behavior
The first time starting Ankaios agents, they find no reusable podman/podman-kube workloads. They create the workloads which all end up in a `ExecRunning` state as expected.

When stopping the Ankaios agents and starting them again, they find all previous workloads as "reusable workloads". The agents are resuming the workloads and they immediately change their state to `ExecSucceeded`.  This means all workloads exit and are not running.

## Expected Behavior
The workload containers should either be started completely anew (no resuming) or they should be resumed in a way that they end up in `ExecRunning` again.

## Steps to Reproduce
The Ankaios `state.yaml` is derived from the example in your documentation and is attached here:
[ankaios.zip](https://github.com/eclipse-ankaios/ankaios/files/13965536/ankaios.zip)

### Ankaios installation
**nodeA**
```
curl -sfL https://github.com/eclipse-ankaios/ankaios/releases/download/v0.2.0/install.sh | bash -s -- -v v0.2.0 -t both -a "--name agent_A --server-url http://{{ SERVER_IP_ADDR }}:25551/" -s "--startup-config /home/ubuntu/state.yaml --address 0.0.0.0:25551"
```
**nodeB**
```
curl -sfL https://github.com/eclipse-ankaios/ankaios/releases/download/v0.2.0/install.sh | bash -s -- -v v0.2.0 -t agent -a "--name agent_B --server-url http://{{ SERVER_IP_ADDR }}:25551/"
```
**nodeC**
```
curl -sfL https://github.com/eclipse-ankaios/ankaios/releases/download/v0.2.0/install.sh | bash -s -- -v v0.2.0 -t agent -a "--name agent_C --server-url http://{{ SERVER_IP_ADDR }}:25551/"
```

### Nodes
- node: nodeA
    - Ankaios server
    - Ankaios agent: agent_A
        - workload: webA (podman)
- node: nodeB
    - Ankaios agent: agent_B
        - workload: webB (podman)
- node: nodeC
    - Ankaios agent: agent_C
        - workload: webC (podman)
        - workload: webD (podman)
        - workload: webE (podman-kube)

All workloads are images of `docker.io/httpd:2.4` (web servers), listening to different ports. Different index.html files are mounted into them. Accessing the web servers for testing happens via curl.

1. Start server and the agents in the correct order and giving them some time to start and pull the images
```
ssh nodeA "sudo systemctl start ank-server"
sleep 10
ssh nodeA "sudo systemctl start ank-agent"
ssh nodeB "sudo systemctl start ank-agent"
ssh nodeC "sudo systemctl start ank-agent"
sleep 30
```
2. Test the agents
```
ssh nodeA "ank get workloads"
ssh nodeA "ank get state"
ssh nodeA "curl localhost:8080"
ssh nodeB "curl localhost:8080"
ssh nodeC "curl localhost:8080"
ssh nodeC "curl localhost:8081"
ssh nodeC "curl localhost:80"
```
All workloads are in `ExecRunning` state and return the content of their index.html.

3. Stop the agents and the server in the correct order (agents first)
```
ssh nodeA "sudo systemctl stop ank-agent"
ssh nodeB "sudo systemctl stop ank-agent"
ssh nodeC "sudo systemctl stop ank-agent"
sleep 10
ssh nodeA "sudo systemctl stopank-server"
```

4. Restart the server and the agents again (exactly the same as 1.)
```
ssh nodeA "sudo systemctl start ank-server"
sleep 10
ssh nodeA "sudo systemctl start ank-agent"
ssh nodeB "sudo systemctl start ank-agent"
ssh nodeC "sudo systemctl start ank-agent"
sleep 30
```

5. Test the agents again (exactly the same as 2.)
```
ssh nodeA "ank get workloads"
ssh nodeA "ank get state"
ssh nodeA "curl localhost:8080"
ssh nodeB "curl localhost:8080"
ssh nodeC "curl localhost:8080"
ssh nodeC "curl localhost:8081"
ssh nodeC "curl localhost:80"
```
All workloads are in `ExecSucceeded` state, curl cannot connect (timeout).
Further restarts lead to exactly the same behaviour.

## Context (Environment)
- 3 fresh AWS EC2 instances (t4g.large)
- Ubuntu 22.04 or SUSE ALP for Automotive
- Podman 4.6.1
- Ankaios release 0.2.0

## Logs
The logs (debug level) of the first execution and the second execution are attached here: [ankaios.zip](https://github.com/eclipse-ankaios/ankaios/files/13965536/ankaios.zip)

## Final result

**To be filled by the one closing the issue.**

**Comment by windsource** [comment]
This is a known problem and will be handled in #5.

**Comment by sboett-dev** [comment]
Thank you for clarification. I could not find a workaround other than reinstalling Ankaios completely on a node that is stuck in `ExecSucceeded` state in order to get the workloads back up and running again.

**Comment by krucod3** [comment]
Container started inside pods are handled differently by Podman (for some reason).
If you are using the podman-kube runtime, you would need to execute: 
`podman pod prune` (with or without sudo depending on start mode)
