### ISSUE TITLE
Separate the proto API into external and internal API

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#172]
## Description

Currently the Ankaios API is specified in one single API file ankaios.proto
This exposes some unnecessary information to the users of Ankaios which only adds confusion. (e.g., Ankaios users do not need to know about the AgentHello message in order to communicate with Ankaios)
We shall separate the API into an external and internal part to make the external API clear and better understandable. 

## Goals

Make the external Ankaios API clearer and more understandable.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by krucod3** [comment]
When looking into the problem, it seems that just separating the file will not work.

The Control Interface currently works with ToServer and FromServer objects. These allow sending `AgentHello` and other messages to the server which can be filtered, but would appear in the documentation. We could define "special" To/FromServer objects for the Control Interface that only contain the request and the response, but that would somehow be confusing ... 

At the end we need a proper definition of the proto for the Control Interface which would be part of Ankaio's API and a definition for the gRPC API which is part of the interchangeable communication middleware. The gRPC API proto should also be part of the `grpc` package and not of the `api`.

The described above can be achieved by splitting the proto file into:
* api/proto/base.proto - defining the base messages like workload
* api/proto/ankaios.proto - the Control Interface of Ankaios
* grps/proto/communication.proto - the gRPC protocol for the gRPC communication middleware

Additionally we currently have the problem that the WorkloadStates cannot be delivered via the Control Interface without an explicit request. With the mixed approach (currently) where everything is in one file, this could have been achieved by just sending all workloadStates to all workloads. The obvious problem with this approach is that not all workloads need the states. We would end up in a lot of message traffic that nobody needs. A solution to this and to the requirement to have a slim pinpointed definition of the Control Interface is, again, as stated above, to have dedicated objects for the Control Interface. The dedicated objects can allow a subscription to events like workload states that are otherwise not needed for the gRPC interface.

A changed Control Interface message structure, the demand on filtering events (maybe you don't want all workload states) and the requirement to allow read only access, would also require a change in the way how the access rights are defined.

After thinking about a couple of possibilities, here the proposed new structure:
``` proto
message ToAnkaios {
  oneof message {
    Request request = 1; // this object would be the same as the one we have currently
    Subscription subscription = 2;
  }
}

message Subscription {
  repeated string workloadStatesFilters = 0;
  repeated string eventsFilters = 0; // events would be a new objects in CompleteState at the level of workloads and workloadStates. events would contain a key-value map.
}

// The following are the access right rules for the Control Interface authorization
message ControlInterfaceAccess {
  AccessRightsRule allow = 0;
  AccessRightsRule deny = 1;
  string mountPoint = 2; // This can be added later if we want to change the mount point of the Control Interface  inside the container or place the interface somewhere else for a native workload
  string workloadPath = 3; // This can be used to mount the Control Interface in pods (for runtimes that support them). The path would specify the name of the pod and the container where the mount should be done. 
}

message AccessRightsRule {
  DesiredStateRule desiredStateRule = 0;
  WorkloadStatesRule workloadStatesRule = 1;
  EventRule eventRule = 2;
}

message DesiredStateRule {
  ReadWriteEnum operation = 0;
  repeated string filterMasks = 1;
  repeated string targetValues = 2;
}

message WorkloadStatesRule {
  ReadSubscribeEnum operation = 0;
  repeated string objectFilterMasks = 1;
  repeated string targetValues = 2;
}

message EventRule {
  ReadWriteSubscribeEnum operation = 0;
  repeated string filterMasks = 1;
  repeated string targetValues = 2;
}

enum ReadWriteEnum {
  RW_READ = 0;
  RW_WRITE = 1;
}

enum ReadSubscribeEnum {
  RS_READ = 0;
  RS_SUBSCRIBE = 2;
}

enum ReadWriteSubscribeEnum {
  RWS_READ = 0;
  RWS_WRITE = 1;
  RWS_SUBSCRIBE = 2;
}

```
With the above definitions, writes to workload states are not allowed per definition. The Schema is extensible to new messages and new rules and is easy to understand. Additionally, good scoping is possible for the subscriptions which would reduce the number of transferred messages.

The `ControlInterfaceAccess` should be an optional field in the workload object. If it is not defined, no control interface would be provided. This would also spare some unnecessary operations on Ankaios' side.

The described above changes are **not** backwards compatible with the current Control Interface definition as the base object `ToServer` would change to `ToAnkaios`. We would need to provide a migrating guide.

**Comment by windsource** [comment]
In general the proposal looks good to me. For the `subscription` we should also allow restricting to an array of workloads rather than just states and events. For `ControlInterfaceAccess ` the default should be to deny all and do not allow anything. I guess the write access always includes read access, or would we need a write access without reading? Maybe we can rename `RW_WRITE` to `RW_READWRITE`.

Not sure what `targetValues` is supposed to be.

**Comment by krucod3** [comment]
I was just going to change the enums to READ_WRITE, so I'm definitely with you here.
The `subscriptions.workloadStatesFilters` should be something like ["instanceName.workloadName=myworkload*", "executionState.state=pending"] which should match all workloads starting with myworkload, e.g., myworkload_1, but only when they are in state pending. Of course one can remove the second filter will get all states.
`targetValues` is something already described in the initial design. It is only applicable when you have write access and restricts the possible values which the workload can set, e.g., starting workloads only on `agent_A`. We don't need to implement it now, it is written here for completeness.

**Comment by krucod3** [comment]
Maybe I don't understand how do you want to restrict the subscriptions to an array of workloads? The idea as written to allow subscriptions only to the objects `workloadStates` and `events` from the complete state. We don't want to allow workloads subscribing to changes of the desired state. The agents (currently) cannot even serve such a request as they do **not** have the complete state, only the server has it. Handling subscriptions should be something the the agent does standalone without having to ask the server for information.

**Comment by windsource** [comment]
There might be use cases where subscriptions to the desired state might be useful. That might be a live dashboard. Also an ingress controller that is controlled via tags on a workload. When traefik works in docker mode it acts like that.
So currently such an ingress controller then needs to poll the desiredState via CompleteState in regular intervals.

**Comment by krucod3** [comment]
Now I understand what you mean. This would definitely be helpful, but would also be harder to implement and maintain. That is what the events were for. The event can be sent that something changes (by whoever made the update) and the "operator" can act upon it. Admittedly this not as convenient, but would work for a start and we can see what the demand on the feature to subscribe for desired state changes is.

Some background about the implementation if we allow subscription to the desired state:
The agents currently only get the workload specifications that they are interested in (workloads they shall run). To provide this feature we can go with one of the following options: 
* the agents shall also get the complete state on every change alongside the added/deleted workloads for them
* or we don't send added/deleted workloads anymore and the agents calculate on their own what they should run (this is a complete rethinking and redoing of the protocol)
* the agents should forward the subscription to the server and the server shall send these events (could be very communication intensive, additionally the server could get overloaded)

We could also add some general system events sent by Ankaios server, like:
* desired state changed

**Comment by krucod3** [comment]
Done.
