### ISSUE TITLE
Documentation: SVGs hard to read in dark mode

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#187]
There are a couple of SVGs in the documentation, like in [here](https://eclipse-ankaios.github.io/ankaios/0.2/architecture/). If you switch the documentation to dark mode, those SVGs are hard to read.

## Current Behavior
SVGs hard to read in dark mode.

## Expected Behavior
SVGs should be easy to read in light and dark mode.

## Steps to Reproduce

1. Goto https://eclipse-ankaios.github.io/ankaios/0.2/architecture/
2. Use the button left of the search field to switch to dark mode.

## Context (Environment)

https://eclipse-ankaios.github.io/ankaios/0.2/architecture/

## Final result

**To be filled by the one closing the issue.**

**Comment by simone-weiss** [comment]
Sth like 
```
![blub](dark.svg#gh-dark-mode-only)
![blub](light.svg#gh-light-mode-only)
```
should be possible

**Comment by windsource** [comment]
https://github.com/squidfunk/mkdocs-material/discussions/2097 might also help.

**Comment by maturar** [comment]
The fix has been implemented.
