### ISSUE TITLE
Fix the Complete state filtering using filter masks

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#196]
When one filters a complete state with a filter mask the resulting object currently contains default values for all other values. This can be misleading as the actual value could differ from the default one. The proto encoding supports empty attributes (everything is optional), but we have defined that a workload spec which is part of a state in the complete state must always have some attributes. Currently this is handled by not defining a serde default for them. Even if we change this logic, and return proto objects with all other attributes empty we risk that somebody implementing against the protocol in her language of choice does handle all optional values with defaults.

As a workaround the filtering for `get state` is now disabled with #191. It is to be defined what the correct behavior is before main can be released as v0.3.

## Current Behavior

Default values were returned until now for the unrequested values which were again stripped in the CLI. The ControlInterface delivers possibly wrong default values.

## Expected Behavior
TBD

## Steps to Reproduce

1. Start a server with a config
2.request complete state using filter mask that requires some specific attribute of a workload spec.

## Context (Environment)
All

## Final result

1. Fix the filtering of the lest level for the WorkloadStatesMap s.t. a filter `workloadStates.agent_B.hello1.9f4dce2c90669cdcbd2ef8eddb4e38
d6238abf721bbebffd820121ce1633f705.state` works. The output can be left in capital camel case for now, e.g., `Running`
1. Fix the unit tests for the filtering
2. Fix the other unit tests
3. check coverage for the unit tests
4. check the output of the ControlInterface (it should return proper objects when filtering and not some strange default values)

**Comment by krucod3** [comment]
After considering some pros and cons, we will go for not considering the required for input values when the filter mask is used. This means that proto will not contain some optional attributes and if a user builds an object from the filtered response, the object will not be usable for a `set state` command without a filter mask or as a manifest in `apply` or the startup config.

Internally we have to take care to not try converting the filtered response to a real object. We should push it as is further down the chain.

**Comment by krucod3** [comment]
The filtering was completely removed removed with [479548c52747f9a0e5759079c2006a3f6a4f2f8d](https://github.com/eclipse-ankaios/ankaios/commit/479548c52747f9a0e5759079c2006a3f6a4f2f8d)
[filtering.patch](https://github.com/eclipse-ankaios/ankaios/files/14511417/filtering.patch)

**Comment by christoph-hamm** [comment]
> After considering some pros and cons, we will go for not considering the required for input values when the filter mask is used. This means that proto will not contain some optional attributes and if a user builds an object from the filtered response, the object will not be usable for a `set state` command without a filter mask or as a manifest in `apply` or the startup config.
> 
> Internally we have to take care to not try converting the filtered response to a real object. We should push it as is further down the chain.

I think it would be best to not use our internal representation in the Ankaios CLI at all. It would be easier to convert directly from the proto objects to serde_yaml/serder_json objects and vice versa. For the get state, the Ankaios CLI should directly convert the proto objects to json. For set state, the Ankaios CLI should directly convert the user input, which is in yaml, to proto objects.

Similar for the server. For get state the Ankaios server first converts the internal representation into a serde_yaml::Value object and applies the field mask to this object (as it is already implemented). Then, the Ankaios server should convert this serde_yaml::Value object directly into the proto object. For set state the Ankaios server first converts the old internal state into the a serder_yaml::Value object and also converts the incoming state directly from proto into a serde_yaml::Value object. The old state and the incoming state are combined according to the field mask. The new state object is then converted to the internal representation again.

To be able to directly use serde on the proto object, we need to configure prost to support serde.

**Comment by krucod3** [comment]
This here is needed for the proper functioning of #22. Without the filtering, the get state with a filter mask and scoped read permissions makes no sense as the complete object is returned in any case.

**Comment by krucod3** [comment]
I tried this approach and removed all internal response representation, trying to return a yaml serialized file generated from the proto generated Rust objects. It kind of works, but a lot of attribution is needed at the build level (tonic_build) to get the serde attributes correctly in order to get the expected outcome.

An alternative would be to write an custom Rust object (or generate it using yaml/json schema) and manually (or as proposed by Christoph using a macro) add conversions between the objects.

**Comment by inf17101** [comment]
I have resolved the TODOs in the production code.

**Comment by inf17101** [comment]
Gabi is testing point 5, the filtering over the control interface.

**Comment by inf17101** [comment]
The control interface examples must be adapted as well, because due to the changes in the proto files they do not work anymore at the moment. I have adapted one example in a pair programming session with Gabi, and the other three examples will be fixed by Gabi the same way. We tested the Filtering with different filter masks for the cpp_control_interface example and the filtering works now.

There is only one thing left: If you declare a custom user type in the proto file then you must construct it inside a workload even if you do not fill or use that type:
`Tags` and `Dependencies` must be allocated and specified even if they are not used (nothing inserted into):
![image](https://github.com/user-attachments/assets/b14139f4-c3f1-4884-a074-5b9968e1d54e)

If you do not construct those types the pipes_channel_task.rs getting the message from the control interface would reject the whole object with error "missing Tags" or "missing Dependencies".

**Comment by inf17101** [comment]
> The control interface examples must be adapted as well, because due to the changes in the proto files they do not work anymore at the moment. I have adapted one example in a pair programming session with Gabi, and the other three examples will be fixed by Gabi the same way. We tested the Filtering with different filter masks for the cpp_control_interface example and the filtering works now.
> 
> There is only one thing left: If you declare a custom user type in the proto file then you must construct it inside a workload even if you do not fill or use that type: `Tags` and `Dependencies` must be allocated and specified even if they are not used (nothing inserted into): ![image](https://private-user-images.githubusercontent.com/42932060/350009814-b14139f4-c3f1-4884-a074-5b9968e1d54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTQwNTcsIm5iZiI6MTcyMTMxMzc1NywicGF0aCI6Ii80MjkzMjA2MC8zNTAwMDk4MTQtYjE0MTM5ZjQtYzNmMS00ODg0LWEwNzQtNWI5OTY4ZTFkNTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDE0NDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzllZWUwYzNhNmE2Yjk5ODAxN2RiMmUzZmE3NzNjZDExOGFhMTczODg1Zjc3ZjA0NmZkOThjYzAyMzQwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F-rVCmSzbSMz-mBaRX_Bdc1o9PJHasvvsLJ-QITK8_Q)
> 
> If you do not construct those types the pipes_channel_task.rs getting the message from the control interface would reject the whole object with error "missing Tags" or "missing Dependencies".

I have fixed it, the conversion function from Workload proto object into internal StoredWorkloadSpec object was expecting values for Tags, Dependencies and RestartPolicy. I have adapted the conversion function. Now the code can be removed in the control interface example, which I have already done now.

**Comment by krucod3** [comment]
All done here.
