### ISSUE TITLE
Extend the Ankaios config and the Ankaios agent to support K8s resources

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#2]
We also need to decide how this is represented in the state. Possible options are:

* not at all, the podman config is different and the podman operator decides depending on the config what this is. The problem here is that we somehow must be able to filter pods out in the CLI. This can still be done by getting all workloads and taking a look in the config, but it is somehow dirty....
* additional runtime for pods, i.e. "podman-pod"
* runtime sub-type, e.g. an optional attribute in the config specifying that this is a pod. This has the benefit that also other runtimes can simulate pods (e.g. containerd).

Note:

Be careful that a pod can have multiple containers inside and podman has to derive a combined state from the in order to deliver the workload execution state.
We can get some inspiration from K8s for the calculation process.

This task includes starting/stopping pods and deriving the workload status.

**Comment by krucod3** [comment]
This will be handled within the #1 issue, no subtask is needed here.
