### ISSUE TITLE
Cleanup PodmanWorkload & PodmanUtils

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#20]
Reported by @krucod3:

## Description

There is currently no clear boarder between the responsibilities of PodmanWorkload and PodmanUtils. PodmanWorkload has unit tests that actually also test PodmanUtils and the podman_api crate. 
The responsibilities hall be correct by making PodmanWorkload the unit with the business logic and PodmanUtils the only wrapper around the podman_api crate.

This would allow us to mock PodmanUtils in PodmanWorkload and simplify and improve the unit tests for the business logic inside the runtime specific Workload PodmanWorkload.

## Goals

Clear separations of responsibilities making the code understandable and maintainable.

## Tasks

tbd.

**Comment by krucod3** [comment]
Will be done with #1
