### ISSUE TITLE
Make a generic RuntimeAdapter out of PodmanAdapter

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#21]
Reported by @krucod3:

## Description

The logic in PodmanAdapter can be generalized to a generic RuntimeAdapter implementation that takes a generic Workload object specified by the workload_trait.rs. The specific object and the name of the specific instance of the RuntimeAdapter will be provided at creation in the agent/src/main.rs

## Goals

DRY principle
Easier maintenance 

## Tasks

tbd.

**Comment by krucod3** [comment]
Will be kind of handled in #1 and is thus obsolete.
