### ISSUE TITLE
Clarify API documentation

### ISSUE THREAD

**Issue by christoph-hamm** [eclipse-ankaios/ankaios#225]
## Description

* On the landing page of the Reference
    * GRPC is not only for during development
    * explain different usage for GRPC (external applications) and the Control Interface (for workloads)
    * current state -> desired state
* In Reference/Protocol Documentation, remove the TOC on top. The first the user should read, is the explanation of the two top level messages. It should be clear that only this two messages are of interest.
* Rename Development -> Contribution
* In [Configuration Structure](https://eclipse-ankaios.github.io/ankaios/main/reference/startup-configuration/#configuration-structure) restart -> restartPolicy
* in the examples we should clearly state that the examples have to be used with the appropriate version of Ankaios (examples from main only with build from main and not with installed binaries)
* the the examples/README.md we shall mention the `shutdown_example.sh` script

**Comment by krucod3** [comment]
The protocol documentation section is autogenerated and cannot be updated that easily. As a workaround (as we are planning to split it), I renamed the section and pushed it to the buttom.

**Comment by krucod3** [comment]
Done.
