### ISSUE TITLE
Update of failed podman workload leaves old container on the system

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#226]
After an update of a failed podman workload for which the container create was successful created, the old container is left on the system and cannot be deleted via Ankaios anymore.

## Current Behavior
Update of failed podman workload leaves old container on the system

## Expected Behavior
The container for the failed workload must be deleted latest during the update (maybe even after the end of the retry).

## Steps to Reproduce

1. Start an nginx workload, e.g., `nginx`, at a mapped port 8080
2. Start a second nginx, e.g., `test_nginx` at a mapped port 8080
3. The last step will cause the start of the workload to fail, as the port is in use
4. Wait until the retry is done (20 sec)
5. Update the `test_nginx` workload (using `ank get state` and `ank set state`), s.t. the port is now 8081
6. The `test_nginx` workload is now running
7. execute a `podman ps -a` and observe that two container exists now for `test_nginx` with different hash values for the config. The one not running is the one with the 8080 port mapping

## Context (Environment)
Manjaro Linux 
Podman 4.9.3

## Logs
``` console
CONTAINER ID  IMAGE                            COMMAND               CREATED         STATUS                    PORTS                 NAMES
b3f6ab60ba7b  docker.io/library/nginx:latest   nginx -g daemon o...  7 minutes ago   Up 7 minutes              0.0.0.0:8081->80/tcp  nginx.7d6ea2b79cea1e401beee1553a9d3d7b5bcbb37f1cfdb60db1fbbcaa140eb17d.agent_A
7ce8660f898b  docker.io/library/alpine:latest  echo Hello Ankaio...  7 minutes ago   Exited (0) 7 minutes ago                        hello3.2aef335312f4e87e60b2b2f91befbe556aaf5159fe0e6a1b804e80a95acf1b1e.agent_B
606a16c06c26  docker.io/library/nginx:latest   nginx -g daemon o...  4 minutes ago   Created                   0.0.0.0:8081->80/tcp  nginx_from_manifest1.7d6ea2b79cea1e401beee1553a9d3d7b5bcbb37f1cfdb60db1fbbcaa140eb17d.agent_A
e433cdd3fc25  docker.io/library/nginx:latest   nginx -g daemon o...  4 minutes ago   Up 4 minutes              0.0.0.0:8082->80/tcp  nginx_from_manifest2.cfef8c463f359e05114ddd6bbb184a3894944b52deeab966e3b0139e74694cf3.agent_A
acc7668a55bf  docker.io/library/nginx:latest   nginx -g daemon o...  19 seconds ago  Up 20 seconds             0.0.0.0:8083->80/tcp  nginx_from_manifest1.848a4ac4f22d018174e335889a21c4864d69cca62d6b66d5eeb2ab1c9db5d801.agent_A
```

## Final result

The solution is described [in the comment below](https://github.com/eclipse-ankaios/ankaios/issues/226#issuecomment-2061317509).

**Comment by maturar** [comment]
The fix has been implemented. The ticket is ready for review.

**Comment by maturar** [comment]
The fix has been reviewed and merged to main.
