### ISSUE TITLE
Deleting a waiting to start workload leaves dirty workload execution state in server

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#227]
If a workload with an unmet dependency is deleted from Ankaios, the deleted state is not propagated to the Ankaios server.

## Current Behavior
`ank get workload` shows the execution state as `Pending(WaitingToStart)` after the workload is deleted via the CLI with `ank delete workload`

## Expected Behavior
The workload execution state removed is sent by the agent to the server and the execution state is removed from the complete state.

## Steps to Reproduce

1. Start an Ankaios server with the `tests/resources/configs/default_config_with_dependencies.yaml` config: `./ank-server --startup-config ../../../tests/resources/configs/default_config_with_dependencies.yaml`
2. Start an Ankaios agent with name `agant_B`
3. Send a delete command via the CLI: `ank delete workload workload_B`
4. Observe the cluster state with `ank get workloads`

## Context (Environment)
Manjaro Linux
Ankaios build from main
Podman 4.9.3

## Logs

``` console
WORKLOAD NAME   AGENT     RUNTIME   EXECUTION STATE           ADDITIONAL INFO
 workload_B      agent_B             Pending(WaitingToStart)
```

Agent logs:
``` console
[2024-04-03T11:48:58Z INFO  ank_agent::runtime_manager] Received a new desired state with '0' added and '1' deleted workloads.
[2024-04-03T11:48:58Z WARN  ank_agent::runtime_manager] Workload 'workload_B' already gone.
```

## Final result

In the reported case where a workload involves a dependency on another workload that does not exist or has not been started yet, the workload is in Pending(WaitingToStart) state, meaning no Podman container for this workload is created. When deleting, the workload was removed from the queue but no message was sent to the server indicating that the workload was deleted. The solution here is to send a message when a workload is deleted from the queue through a delete request.

**Comment by lingnoi** [comment]
In the reported case where a workload involves a dependency on another workload that does not exist or has not been started yet, the workload is in Pending(WaitingToStart) state, meaning no Podman container for this workload is created. When deleting, the workload was removed from the queue but no message was sent to the server indicating that the workload was deleted. The solution here is to send a message when a workload is deleted from the queue through a delete request.
