### ISSUE TITLE
Refactor and improve CLI code

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#229]
## Description

The `ank` CLI code is currently all located in the cli_command.rs module with now more than 1000 lines of code.
The CLI shall be spitted into smaller modules for better maintainability. 
Additionally the design documentation of the CLI must be updated regarding structural view and the tags of the requirements. Currently there are tags for features, e.g., GetWorkload, instead of components.

## Goals

Improve maintainability of the CLI

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [x] Refactor the code
- [x] Update SwDD

**Comment by maturar** [comment]
The PR with the implementation has been reviewed and merged into `main`.
