### ISSUE TITLE
Upgrade GH Actions deprecated upload and download actions

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#255]
## Description

Github Actions deprecates the following actions:

- actions/upload-artifact
- actions/download-artifact

[https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.blog%2Fchangelog%2F2024-04-16-deprecation-notice-v3-of-the-artifact-actions%2F&data=05%7C02%7C%7C9f658521474a488821e608dc64389198%7Ce764c36b012e4216910d8fd16283182d%7C0%7C0%7C638495441368104599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=VCgMS63w0pMoiDOgMCHPdKTxuwPbREXcOGarC6ncbEQ%3D&reserved=0)
[https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.blog%2Fchangelog%2F2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions%2F&data=05%7C02%7C%7C9f658521474a488821e608dc64389198%7Ce764c36b012e4216910d8fd16283182d%7C0%7C0%7C638495441368115771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=UTrxr%2B6bAmcJtSUuKPL1dCKHjG7IxZuw4LvRm57khWY%3D&reserved=0)

The following versions are deprecated and will stop working in the not so near future:

* v1 and v2: from 30/06/2024
* v3: from 30/11/2024

It is highly encouraged to update to v4 of these actions asap to avoid any disruption.

Currently, we are using v3 for both actions.

Upgrade the versions to a stable v4.x.y version.

## Goals

Upgrade the versions to a stable v4.x.y version.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by inf17101** [comment]
Duplicate of #254

**Comment by krucod3** [comment]
Duplicated as written above
