### ISSUE TITLE
Add a new ank apply command the the CLI

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#26]
Reported by @lingnoi:

## Description

Pain point: 
To update the current state the user needs to run the following command like `ank set state -f new_state.yaml currentState.workloads.nginx.restart ..`. Here the user needs to specify the object field mask for any desired field that needs to be changed.

Solution Proposal:
To reduce the effort for the user for specifying the object field mask to update the current state the user could just provide a compact state object that contains *only the fields that need to be changed* so that `ank` could automatically extract those fields as object field masks and produce an update request.
So the user could then call e.g:
`ank set state --compact new_state_compact.yaml`

Content of `new_state_compact.yaml` could be:
```yaml
currentState:
   workloads:
        nginx:
           restart: false
        hello1:
           restart: true
```

`ank` could then produce the following parameters for the update request:
```
(PSEUDO)
UpdateRequest:
    - new_state_compact 
    - ["currentState.workloads.nginx.restart", "currentState.workloads.hello1.restart"]
```

## Goals

see description

### Summary

As discussed, the following to be supported:
 
* new layout of the input yaml file:
 
```yaml
workloads:
  service1:
    ...
  service2:
    ...
configs:
  config1:
    ...
  config2:
    ...
```
* Only one command: `ank apply <file(s)>`, `ank apply -d <file(s)>`
* Processing from stdin: `cat workloads.yaml | ank apply`
* Processing from file(s): `ank apply workloads1.yaml workloads2.yaml ...`
* Deleting workloads from stdin: `cat workloads.yaml | ank apply -d`
* Deleting workloads from file(s): `ank apply workloads1.yaml workloads2.yaml ...`
* Processing all workloads on given agent name (regardless if a workload already has an agent name assign in the YAML):  `ank apply --agent agent_A workloads1.yaml ...`
* For `ank apply -d` there is no `--agent` supported or just ignored
* Generating an error when neither the agent name is specified in the YAML nor provided through the `--agent ` option.
* Processing from multiple files via globbing pattern evaluated by the shell:  `ank apply *.yaml`

## Tasks
- [ ] Extend the SW design for handling 'ank apply ..' command
- [ ] Implement `ank apply` command

**Comment by krucod3** [comment]
We should think about all possible options here, e.g.:
* ank run workload also accepts a file
* Should run update things?
* aliases or new commands for:
** update or set?

**Comment by windsource** [comment]
Currently `ank run workload` takes the command line options:

* `--runtime <RUNTIME_NAME>`
* `--config <RUNTIME_CONFIG>`
* `--agent <AGENT_NAME>`
* `<WORKLOAD_NAME>`

I would prefer if one or several of these options can optionally be passed in a yaml file like:

```
ank run workload -f myworkload.yaml
```

with `myworkload.yaml` being

```
nginx:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_MOST_ONCE
    accessRights:
      allow: []
      deny: []
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      image: docker.io/nginx:latest
      commandOptions: ["-p", "8081:80"]
```

When the `-f` option is used then the name of the workload must not be passed via command line but is taken from the yaml file. The runtime, agent and runtimeConfig are taken from the yaml if present, otherwise they can also be passed via command line. This might be a use case when the user wants to have a yaml that contains all but not the agent name as that could differ for each deployment target.

`ank run workload` shall then not only start workloads but also update those from my point of view. Maybe we should rename it to `apply` like in `kubectl`?

Maybe we should also allow starting/updating of more than one workload using that command. It would be very convenient. Then options passed on the command line would apply to all workloads provided in the yaml file.

**Comment by krucod3** [comment]
Using the run for multiple workloads at the same time could be convenient, but is very close to what the set state does. Beside that, providing a config that is applied to all workloads would degrade the operation to clone-creation as the config is currently read as one piece (we cannot change small parts of the runtime config as we don't want to know what is inside).

How about the following:
* `ank run` takes an optional -f <file_path> that accepts all normal options (as suggested above), and additionally an (optional in case -f is supplied) workload name. If an option is provided, the content of the provided file is overwritten (incl. name). This option also only allows a single workload in the file and fails if the workload already exists (s.t. this would be the "I don't want to break something" action).
* `ank update` is the same as `ank run`, but additionally overwrites a workload (updates) in case it exists (allowing an "I know what I'm doing" action).
* `ank apply` is a kind of a convenience layer on top of `ank set` and accepts only a file without any options that contains a list of workloads with a root element `workloads:` (a subset of the complete state).

@christoph-hamm what do you think about this?

**Comment by windsource** [comment]
Consider the following use case:

An application developer has created an application, that consists of three workloads and one config (config not implemented yet in Ankaios but planned for the future). An integrator get this application setup and wants to add this application to an Ankaios system with already 100 workloads running without interrupting the existing workloads.

This leads to two requirements:

**1. Format for passing an application**

We need a (file) format such that an application developer can pass an application to an integrator. That file format should allow different kinds like workloads and configs. The format should work for both modifying the current and stored state.

Example:

```
workloads:
  service1:
    ...
  service2:
    ...
configs:
  config1:
    ...
  config2:
    ...
```

The agent name is optionally in this file. If different workloads shall run on different agents then the application developer might already provide the desired agent names but if all workloads shall run on one agent then maybe the integrator selects the agent later on.

**2. CLI for modifying the state**

We need a CLI command that takes such a file and modifies either the stored or saved state. I think the `ank set state` is not suited for that. For my point of view `set` is the wrong keyword here is we want to modify the state rather then exchange an existing state. Please note that this new command shall be **atomic**. If the CLI would internally call `ank get state` then modify  the result and call `ank set state` the operation would not be thread safe. Probably we will have different applications that want to start and stop workloads and those applications should not disturb each other. The new command shall also allow passing an agent which will then be used be all workloads in the file. From my point of view `ank apply` would be a good name for that new command which by default modifies the current state but with an additional parameter could also modify the saved state.

**Comment by krucod3** [comment]
As clarified the `apply` shall also support an optional `--agent`. 
Please check how we can and if we want to also support stdin for input. Please also note that we already support file input and stdin for `set state`. We should take case that the CLI behaves consistently for all commands (also for start server see #34 ).

**Comment by windsource** [comment]
For `ank apply` we should support stdin and also a wildcard mask like `*.yaml`.

**Comment by windsource** [comment]
We also need to think about how we can reverse such an operation. In Kubernetes there is `kubectl apply -f workloads.yaml` and that can be reversed with `kubectl delete -f workloads.yaml`. However for Ankaios we have already used `ank delete` so maybe we need another keyword for that.

**Comment by lingnoi** [comment]
> We also need to think about how we can reverse such an operation. In Kubernetes there is `kubectl apply -f workloads.yaml` and that can be reversed with `kubectl delete -f workloads.yaml`. However for Ankaios we have already used `ank delete` so maybe we need another keyword for that.

According to this [thread](https://stackoverflow.com/questions/57683206/what-is-the-reverse-of-kubectl-apply) 
![image](https://github.com/eclipse-ankaios/ankaios/assets/42992756/b7408e0b-ac1a-493d-98dc-9afbec0c6acf) there is no a real "reverse to a previous state" in in Kubernates, but it just removes the workloads defined in the yaml. Is this the behavior you meant by "reverse"?

**Comment by windsource** [comment]
Yes, with reverse I mean remove.

**Comment by lingnoi** [comment]
> Yes, with reverse I mean remove.

What is then the difference to `ank delete`?

**Comment by windsource** [comment]
We can also integrate that in `ank delete` if that fits. Currently ank delete always requires the keyword `workload`. Maybe we can have that optional if the option `-f` is provided.

**Comment by lingnoi** [comment]
Just to summarize what needs to be supported:
- Processing from stdin: `cat workloads.yaml | ank apply -f -` or `cat workloads.yaml | ank apply` (to be decided)
- Processing from file: `ank apply -f workloads.yaml`
- Deleting workloads from stdin: `cat workloads.yaml | ank delete -f -` or `cat workloads.yaml | ank delete` (to be decided)
- Deleting workloads from file: `ank delete -f workloads.yaml`
- Processing only workloads on given agent name:  `ank apply --agent agent_A -f worklaods.yaml`, `ank delete --agent agent_A -f worklaods.yaml`

**Comment by windsource** [comment]
Later on we also need an option such that not the current state but the saved state is modified.

**Comment by krucod3** [comment]
Looks great!
Just one point, actually we don't need the `--agent` at the `ank delete` command, as the workload names are the only identifiers.

**Comment by lingnoi** [comment]
As discussed with @windsource, just to summarize what needs to be supported:
- new layout of the input yaml file: 
```yaml
workloads:
  service1:
    ...
  service2:
    ...
configs:
  config1:
    ...
  config2:
    ...
``` 
- Only one sub command: `ank apply <file(s)>`, `ank apply -d <file(s)>`
- Processing from stdin: `cat workloads.yaml | ank apply` 
- Processing from file(s): `ank apply workloads1.yaml workloads2.yaml ...`
- Deleting workloads from stdin: `cat workloads.yaml | ank apply -d
- Deleting workloads from file(s): `ank apply workloads1.yaml workloads2.yaml ...`
- Processing all workloads on given agent name (regardless if a workload already has an agent name assign in the YAML):  `ank apply --agent agent_A workloads1.yaml ...`
- Generating an error when neither the agent name is specified in the YAML nor provided through the `--agent ` option.
- Processing from multiple files via globbing pattern evaluated by the shell:  `ank apply *.yaml`

**Comment by krucod3** [comment]
> Generating an error when neither the agent name is specified in the YAML nor provided through the --agent  option.
Didn't we wanted to assign the workloads to an `empty` agent ("")?

**Comment by krucod3** [comment]
We agreed that we shall require an agent and generate an error when non is specified. If somebody wants an "empty" agent, this can be explicitly specified with --agent "" or agent: ""

**Comment by krucod3** [comment]
The internal set state command used by the CLI shall generate a filter mask containing all workloads specified in the input files.
