### ISSUE TITLE
Ank CLI `run workload` and `delete workload` use wrong requests

### ISSUE THREAD

**Issue by christoph-hamm** [eclipse-ankaios/ankaios#262]
For change adding or remove a workload, only a `UpdateStateRequest` should be used

## Current Behavior

Currently the Ank CLI for the command `run workload` and `delete workload` is implemented as follows:

1. Get the complete state from the Ankaios server
2. Change this state to match the new desired state
3. Use `UpdateStateRequest` with this new state and **without** `updateMask`

## Expected Behavior

The Ank CLI should not first get the current state,
but only use one `UpdateStateRequest` with an `updateMask` containing the workload which should be altered.
For the `run workload` command, the state needs to contain only this workload in the `desiredState`.
For the `delete workload` the state can be empty.

Always setting the complete state is dangerous,
as it is possible that the state on the Ankaios server is changed by another process/person while the state is manipulated locally.
This could lead to changes being lost.

## Final result

**To be filled by the one closing the issue.**

**Comment by inf17101** [comment]
PR was merged.
