### ISSUE TITLE
Documentation for podman-kube options is wrong

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#285]
This issue was found by @sboett-dev.
It seems that the podman-kube runtime config documentation is wrong:
```
generalOptions: [<comma>, <separated>, <options>]
play_options: [<comma>, <separated>, <options>]
down_options: [<comma>, <separated>, <options>]
manifest: <string containing the K8s manifest>
```
It defines the options as a mixture of snake case and camel case, where actually camel case is required.

## Current Behavior
Wrong documentation (see above).

## Expected Behavior
The documentation gives a correct example

## Steps to Reproduce

1.
2.
3.
4.

## Final result

**To be filled by the one closing the issue.**

**Comment by sboett-dev** [comment]
I can confirm that
```
generalOptions: [<comma>, <separated>, <options>]
playOptions: [<comma>, <separated>, <options>]
downOptions: [<comma>, <separated>, <options>]
manifest: <string containing the K8s manifest>
```
works.

**Comment by krucod3** [comment]
Done.
