### ISSUE TITLE
Basic performance figures

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#3]
## Description

For presenting Ankaios and comparing it with existing orchestrators some numbers on performance and resource usage would be helpful.

## Goals

- RAM usage of server and agent has been measured (simple measurement sufficient, htop etc.)
- ~~Time from startup an agent until Podman is triggered, to get the overhead, has been measured~~
- Raspi is used for performance measurements
- ~~Measure RAM and CPU usage of Ankaios with (a) with no workloads and (b) with 200 container~~
- Documentation has been enhanced by those figures
- Define minimum system requirements

## Tasks

- [x] Perform measurements
- [x] Enhance documentation by describing environment and measurements

**Comment by krucod3** [comment]
We got a proposal from the community to provide the results in a format similar to the one for k3s:
https://docs.k3s.io/reference/resource-profiling

**Comment by windsource** [comment]
Maybe we could also add something to Ankaios itself. The server could log the time it took to setup the start state or the CLI (with an option) prints the time it took to start a specific workload.

**Comment by windsource** [comment]
See also discussion in #188.
