### ISSUE TITLE
Remove WorkloadStateDB from Software Design documentation

### ISSUE THREAD

**Issue by christoph-hamm** [eclipse-ankaios/ankaios#312]
The Software Design Documentation still mentions the `WorkloadStateDB`. As this component has been removed, the documentation needs to be updated.

**Comment by inf17101** [comment]
Isn't it already fixed within the PR #301 commit (https://github.com/eclipse-ankaios/ankaios/pull/301/commits/eeafde86630b9ed5739b80feae23612569781622)?

**Comment by maturar** [comment]
The commit eeafde86630b9ed5739b80feae23612569781622 in the PR #301 removed the `WorkloadStateDB` only partially. There are some leftovers in the SWDD of the Ankaios server.

**Comment by krucod3** [comment]
This here is done. Thanks @maturar!
