### ISSUE TITLE
Improve mTLS error messages upon wrong field values in the Ankaios CLI

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#326]
## Description

Currently, if the user enters a wrong path for the certificates or key in an Ankaios CLI, then the error message is "Channel preliminary closed." which is not helpful to the user since it is an internal Rust channel error message. This is independent of using the environment variables or the cli arguments directly.

1. Execute the script `tools/certs/create_certs.sh` to create certificates for development
2. Start the server and agent with certificates
3. Execute an ank cli command and provide an invalid file path to some of the arguments, e.g.:
```
./ank -v --ca_pem .certs/ca.pem --crt_pem .certs/cli.pem --key_pem asdfg get workloads
```

You should see the following error message:

![image](https://github.com/user-attachments/assets/441f1b35-5852-4523-92a3-b9accbae7692)

## Goals

Enhance the Ankaios CLI to output helpful error messages when an mTLS setting has an invalid value.

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Output "file path does not exist" as error message
- [ ] Analyze if not just the invalid file path can be output, but to output a Certificate Error even it is rejected due to other reasons (Maybe this needs to be included into the request handling and the communication middleware)

**Comment by inf17101** [comment]
The reason is that the polling in the cli does not know when certificates are rejected by the server since it is not contained inside the response and the from_server channel object is in this case `None` since the channel is closed:
     
```
    // server_connection.rs:117
    let poll_complete_state_response = async {
            loop {
                match self.from_server.recv().await {
                    Some(FromServer::Response(Response {
                        request_id: received_request_id,
                        response_content: ResponseContent::CompleteState(res),
                    })) if received_request_id == request_id => return Ok(res),
                    None => return Err("Channel preliminary closed."),
                    Some(message) => {
                        // [impl->swdd~cli-stores-unexpected-message~1]
                        self.missed_from_server_messages.push(message);
                    }
                }
            }
        };
```

**Comment by GabyUnalaq** [comment]
Currently working on this.

**Comment by GabyUnalaq** [comment]
This issue was solved and solution merged. It can be closed now.
