### ISSUE TITLE
Sporadic failing of grpc itests

### ISSUE THREAD

**Issue by christoph-hamm** [eclipse-ankaios/ankaios#347]
The grpc itests fail sporadically. 

## Steps to Reproduce

1. Run `cargo test` many times

## Context (Environment)

Current main (1a84057).

## Logs

    failures:
    
    ---- grpc_tests::itest_grpc_communication_client_cli_connection_grpc_server_received_update_state stdout ----
    thread 'grpc_tests::itest_grpc_communication_client_cli_connection_grpc_server_received_update_state' panicked at 
    grpc/tests/grpc_test.rs:449:9:
    assertion failed: matches!(result,
        Ok(Some(ToServer::Request(Request{ request_id, request_content: _ }))) if
        request_id.contains(test_request_id))
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    
    
    failures:
        grpc_tests::itest_grpc_communication_client_cli_connection_grpc_server_received_update_state
    
    test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s
    
    error: test failed, to rerun pass `-p grpc --test grpc_test`

## Additional Information

For the failing test above, the result has been `Ok(None)`.

Original I thought this failures are caused by some itests using the same port and them crashing because of parallel execution, but using a different port for each test does not fix the issues. The problem persist even if changing to random port numbers.

## Final result

**To be filled by the one closing the issue.**

**Comment by inf17101** [comment]
I haven't looked into the test yet, but if we turn the `matches!` into an `assert_eq!` we can see which values are changing sporadically.

**Comment by inf17101** [comment]
PR merged. I close this in the meanwhile. It will be reopened again if the grpc itests will be failing again.
