### ISSUE TITLE
Definition of done in the PRs points to the development guidlenes

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#35]
## Description

Definition of done does not point to the coding guidelines. Maybe a general link to the development section of the documentation can be added. 
We noticed this during reviewing #30

## Goals

Make sure all contributors follow the development processes of Ankaios.

## Tasks

- [ ] do it 😉

**Comment by krucod3** [comment]
The DoD shall also request the documentation to be up to date.

**Comment by windsource** [comment]
This should be done as part of #36 IMHO.

**Comment by krucod3** [comment]
Closed in favor of #36.
