### ISSUE TITLE
Update of contribution guidelines

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#36]
## Description

Currently we have several locations that describe how contributions shall be performed:

1. Contribution guidelines are in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md). 
2. PR checklist in [PULL_REQUEST_TEMPLATE.md](https://github.com/eclipse-ankaios/ankaios/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
3. Guidelines in the documentation like the [Rust coding guidelines](https://eclipse-ankaios.github.io/ankaios/development/rust-coding-guidelines/) and the [Documentation guidelines](https://eclipse-ankaios.github.io/ankaios/development/documentation-guidelines/).

## Goal

I think that usually the `CONTRIBUTING.md` file is considered as the starting point for contributors and thus shall reference all other guidelines.

### Summary

`CONTRIBUTING.md` file is considered as the starting point for contributors and references all other guidelines. To ensure that the contributing guideline is also followed, it shall be referenced in the PR checklist in PULL_REQUEST_TEMPLATE.md

### Tasks

- [x] Update  `CONTRIBUTING.md` s.t. it requests:
** compliance to the following guidelines:
*** code of conduct 
*** Rust coding guidelines
*** unit verification strategy
** making sure that the following documents are also up-to-date:
*** software design incl. linkage in code and tests
*** Ankaios user documentation (if adding new features)
- [x] Update PULL_REQUEST_TEMPLATE.md to request compliance to the `CONTRIBUTING.md`

**Comment by krucod3** [comment]
I've updated the first task with more information and added a new task to reference the `CONTRIBUTING.md` in the definition of done for the pull requests (PULL_REQUEST_TEMPLATE.md checklist).

**Comment by krucod3** [comment]
Fixed with #66
