### ISSUE TITLE
Implement shell completion for configs

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#391]
Adapt the existing shell completion to support also shell completion for the `desiredState.configs` field.

Tasks:

- [ ] Implement functionality
- [ ] Add utests

**Comment by windsource** [comment]
@inf17101 Shell completion always relates to a cli command. For `ank set state` this is already implemented in #389. When #392 is implemented then this also needs to get shell completion.

**Comment by windsource** [comment]
Shell completion for `ank set state` has already been added in #389. For `ank delete config` and `ank get configs` it has still to be added (maybe as part of #392).

**Comment by windsource** [comment]
Remaining part implemented as part of #400.
