### ISSUE TITLE
Add a new subcommands  `ank delete config` and  `ank get configs`

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#392]
Add a new subcommands `ank delete config` and `ank get config` extending the existing `ank delete` and `ank get`.

The output of `ank get config` shall be like:

```text
CONFIG
my_config1
my_config2
```

Tasks:
- [x] Implement the sub command
- [x] Add utests
- [x] Add stest(s)
- [x] Adapt requirements
- [x] Add shell completions

**Comment by krucod3** [comment]
Just a reminder - we should support both config and configs as a keyword, as done for workload(s)

**Comment by HorjuRares** [comment]
I'll tackle this one

**Comment by windsource** [comment]
`ank get configs` should provide a table like:

```text
CONFIG
my_config1
my_config2
```

**Comment by krucod3** [comment]
All done here
