### ISSUE TITLE
Api version not enforced when using ank apply command

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#395]
The Ankaios server accepts a new state constructed through the `ank apply` command even if the api version does not match to the one on the server.

## Expected Behavior

Api version shall be enforced and the state rejected with a proper error message.

## Steps to Reproduce

1. Apply the following Ankaios manifest with some wrong apiVersion string like:
```yaml
apiVersion: v3
workloads:
  nginx:
    runtime: podman
    agent: agent_A
    runtimeConfig: ""
```
2. You can see that the server is accepting it through the `ank apply` command, but rejecting it when fetching a new state via `ank get state` and inserting a wrong apiVersion string and sending the new state with `ank set state`.

## Context (Environment)

Linux
all platforms
all runtimes

## Additional Information

The same problem is already in version v0.4.1 like I have tested and maybe in previous versions as well.

## Final result

**To be filled by the one closing the issue.**

**Comment by krucod3** [comment]
Let's add an stest for this too. Best with multiple manifests.

**Comment by HorjuRares** [comment]
I will tackle this one.
