### ISSUE TITLE
Ank CLI set state fails when providing a new state containing only the changed field values

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#397]
In the user documentation the `ank set state` command providing a new state with only the changed fields (e.g., restartPolicy) fails with:

- missing field `agent`
- missing field `runtimeConfig`
- missing field `runtime`
- missing field `apiVersion`

This is in the section [Working with CompleteState](https://eclipse-ankaios.github.io/ankaios/main/reference/complete-state/#object-field-mask).

Currently, providing only the changed field like `restartPolicy` (like in the user doc example) is not possible:

```yaml
desiredState:
  workloads:
    nginx:
      restartPolicy: NEVER
```

The command of the user doc fails: `ank -k set state desiredState.workloads.nginx.restartPolicy new-state.yaml`

It complains about missing fields and apiVersion. The apiVersion is obviously missing, but it shall be possible to provide only the changed fields when providing the correct update mask afterwards without providing `agent`, `runtimeConfig` and `runtime` if the workload already exists.

## Current Behavior

The Ank CLI set state command does not accept minimum required information for the new state.

## Expected Behavior

Ank CLI shall support providing only the changed field values if the workload exists in the desiredState.

## Steps to Reproduce

Execute the Working With CompleteState section's set state command with changing the restartPolicy field on the current main branch. It fails.

## Logs

Example error message:
```text
error: Failed to set state: 'Could not serialize YAML object: 'missing field `agent`''
```

## Additional Information

The error is thrown from the ank cli: `ank/src/cli_error.rs` which has to do with the serde_yaml parsing:

```rust
CliError::YamlSerialization(message) => {
    write!(f, "Could not serialize YAML object: '{message}'")
}
```

Potentially related PRs from the past: #340, #383 

## Final result

**To be filled by the one closing the issue.**

**Comment by krucod3** [comment]
According to @inf17101, this was working correctly in v0.4.1, so it's an unreleased regression on main => ignore for release + v0.5.0

**Comment by HorjuRares** [comment]
I can also tackle this one.

**Comment by krucod3** [comment]
The regression is fixed, but we still to fix the real problem. 
@HorjuRares, please link the new issue here. We will take care of it in the next release.
