### ISSUE TITLE
Workload stuck in "Pending(Initial)"

### ISSUE THREAD

**Issue by Ricardicus** [eclipse-ankaios/ankaios#401]
I am trying out Ankaios and tested the standard workload provided in the reference:

```
$ cat /etc/ankaios/state.yaml 
# Per default no workload is started. Adapt the file according to your needs.
apiVersion: v0.1
workloads:
   nginx:
     runtime: docker
     agent: agent_A
     restartPolicy: NEVER
     tags:
       - key: owner
         value: Ankaios team
     runtimeConfig: |
       image: docker.io/nginx:latest
       commandArgs: ["--insecure"]
       commandOptions: ["-p", "8081:80"]
```

However, I changed the runtime to 'docker'.
The workload is not starting properly, and I get no information in journalctl on why.

## Current Behavior
This is what it looks like:

```
$ ank -k apply /etc/ankaios/state.yaml
Successfully applied the manifest(s).
Waiting for workload(s) to reach desired states (press Ctrl+C to interrupt).

WORKLOAD NAME   AGENT     RUNTIME     EXECUTION STATE    ADDITIONAL INFO
nginx           agent_A   docker    / Pending(Initial)
```

The execution state does not change from pending to running.

## Expected Behavior
I expected things to go the way they do in the reference. I Expected it to be indicating that the workload is indeed running.

## Steps to Reproduce

1. Follow the reference guide from: https://eclipse-ankaios.github.io/ankaios/latest/usage/quickstart/

## Context (Environment)

I am running this on an aarch64 machine with a somewhat customized Linux OS built with Yocto, based on kirkstone.

## Logs

```
$ journalctl -t ank-server
Oct 23 11:35:32 syslogic-brla4nx ank-server[1121]: [2024-10-23T11:35:32Z WARN  grpc::server] !!!ANKSERVER IS STARTED IN INSECURE MODE (-k, --insecure) -> TLS is disabled!!!
Oct 23 11:35:32 syslogic-brla4nx ank-server[1121]: [2024-10-23T11:35:32Z INFO  ank_server::ankaios_server] Starting...
Oct 23 11:35:32 syslogic-brla4nx ank-server[1121]: [2024-10-23T11:35:32Z INFO  grpc::from_server_proxy] Agent agent_A not found, workloads not sent. Waiting for agent to connect.
Oct 23 11:36:06 syslogic-brla4nx ank-server[1121]: [2024-10-23T11:36:06Z INFO  ank_server::ankaios_server] Received AgentHello from 'agent_A'

```

## Final result

**To be filled by the one closing the issue.**

**Comment by windsource** [comment]
@Ricardicus Ankaios currently support two runtimes: `podman` and `podman-kube`. A `docker` runtime is currently not supported. In your situation the Ankaios server waits until an agent with a `docker` runtime will connect and that's why the workload's status is `Pending(Initial)`.

So installing Podman and changing the `runtime` field to `podman` should fix the problem (see also [Installation](https://eclipse-ankaios.github.io/ankaios/latest/usage/installation/) and [Quickstart](https://eclipse-ankaios.github.io/ankaios/latest/usage/quickstart/)).

**Comment by Ricardicus** [comment]
That explains it. Thanks!
