### ISSUE TITLE
Improve error output and traces in the ank CLI

### ISSUE THREAD

**Issue by krucod3** [eclipse-ankaios/ankaios#49]
## Description

Currently the ank CLI logs a lot of error as log messages instead of writing the errors to stderr. Additionally log messages should be used only for debugging purposes and thus only debug traces should be allowed in the CLI

## Goals

Define, document and apply a clear concept about logging, outputting errors and exiting with proper exit codes for the ank CLI.

### Summary

We have decided to implement its own tracing in the CLI. Crates regarding tracing either do not provide what we need or they are too complex for this task. The concept is written in the comment and it is also described in the `swdesign`.

### Tasks

- [x] Clarify the concept and write it down as a comment.
- [x] Implement the concept. See #53

**Comment by maturar** [comment]
**Short brainstorming about the concept:**

* Tracing functions:
  * **output_debug**(message) - just debug and continue
  * **output_and_exit**(message) - prints a message (a success) **and calls exit(0)**
  * **output_and_error**(message) - prints the error message **and calls exit(1)**
*  If there is an internal error in the CLI, the CLI shall write a message to the user (something like "internal error occurred"). The flag (-v) shall provide detailed information.
* CLI shall have special functions for the "CLI tracing". The developer will understand that we want to do a trace (it is not a forgotten debug print).
  * **TODO: how to hide the env_logger (so the user is not able to create info or warning logs)?**
* We can use flags:
  * ```-v``` to activate the debug traces 
* Errors have no flag. They will always be printed to the user.
* The debug traces will be activated with the flag "verbose". The flag will activates the output_debug function or sets the log level to "debug".
* There is no other log level except of debug and error.

**Comment by maturar** [comment]
**How to implement the tracing in CLI**
The goal is to have own tracing in the CLI and hide the standard logger. The point is that the developer shall use our proprietary tracing functions and not the standard ones.

I have checked several crates regarding tracing. There are two problems there. One problem is that some crates are just an extension of the standard logger. In other words they do not hide the standard logger. This violates our main requirement. The second problem is that some crates are able to hide/replace standard logger. But they are very complex. It would be overkill to use a complex solution for such tiny task. 

Kaloyan had an idea to check tracing in the [rustup](https://github.com/rust-lang/rustup/tree/master). Particularly [this](https://github.com/rust-lang/rustup/blob/master/src/cli/log.rs). This seems to be what we want.

**Comment by maturar** [comment]
I have checked the tracing from rustup. Unfortunately they cannot be used in the Ankaios as it is. They require many dependences. In other words the implementation is too complex. But the idea with macros which call a formatting function seems to be good.

**Comment by maturar** [comment]
The pull request has been reviewed and merged to the main.
