### ISSUE TITLE
Ank cli connection timeout when deleting a not started workload from the current state

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#57]
When executing `ank delete workload <name>` with a name from an workload that is in the current state but not initial started yet,
the Ank cli hangs up for some seconds and outputs an error showing a connection timeout.

## Current Behavior

The Ank cli hangs up and outputs a connection timeout error when trying to delete a not started workload of the current state.

## Expected Behavior

The Ank cli shall not hang up and shall avoid to output a connection timeout error.
## Steps to Reproduce

1. Start the Ankaios server with the current example config (ankaios/server/resources/startConfig.yaml) but for simplicity remove the workload api example workload from the config.
2. Start only Ankaios agent with name `agent_A` (it shall start nginx according to the default config)
3. Do not start the agent_B with the other workloads
4. Delete a workload of agent_B which is in the current state but not started, because agent_B was not started yet. Execute `ank delete workload hello3`. The Ank cli behaves like described above.

## Context (Environment)

Linux
Ank cli
Podman Runtime

## Logs

![image](https://github.com/eclipse-ankaios/ankaios/assets/42932060/9e0edbcb-1c98-4bb9-a8bb-b40354adedcf)

## Final result

Fixed with #100, not reproducible anymore because the timeout of the cli was completely removed in #100.

**Comment by maturar** [comment]
I was not able to reproduce the issue. Neither with the release 0.1.0 nor with the current main. Tested with Ubuntu 20 and Manjaro. @inf17101 could you re-test the issue again, please?

**Comment by inf17101** [comment]
Fixed with #100, with older commit before the server crash fix (https://github.com/eclipse-ankaios/ankaios/tree/503ac73c866fa40d04ec6c3645ea5f3540516bd4) it is present. So, with the fix of #100 it is not reproducible anymore.
