### ISSUE TITLE
Update state via Ankaios CLI is not executed if runtime needs to much time to delete workload

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#67]
A update or add of a workload via the Ankaios CLI is not executed, if the user deletes a workload out of the current state, tries to update the state again by adding this workload again and the runtime is still busy with deleting the workload. If the user then retries to update the state, when the workload is deleted by the runtime, then the Ankaios orchestrator does not start the workload. In addition the user does not get a feedback of the Ankaios CLI about a reason.

## Current Behavior

The user deletes a workload out of the current state.
The runtime needs a long time to delete the workload.
The user tries to update the current state with adding this deleted workload again.
The add of the workload fails (this is expected) because no container with the same name can exist. 
The user does not look into Agent logs, because there is no feedback of the Ankaios CLI that the set state fails,
so the user decides to retry the update of the current state.
If on the second try the runtime was able to delete the workload already, the Ankaios server would not execute the update, because from the view of the Ankaios server the current state has not changed compared to the first try to update the state.
The user does not receive any feedback over the Ankaios CLI, the workload is then just not deployed and the user wonders why...

## Expected Behavior

The workload shall be deployed by Ankaios even if the runtime takes longer time to delete the workload when the user tries to add the same workload again via an update of the current state.

## Steps to Reproduce

1. Start Ankaios with an initial state containing a workload that needs time to delete for the runtime.
2. Delete the workload via the Ankaios CLI: `ank delete workload <workload_name>`
3. During the runtime is busy with deleting the workload, update the current state of the Ankaios server with the Ankaios CLI: `ank set state -f currentState.yaml currentState.workloads.<workload_name>`
4. The first update state request fails, because it is logical that the runtime cannot deploy the workload while it is still existing due to a name conflict.
5. Wait until the runtime has deleted the workload.
6. Update the current state again by executing: `ank set state -f currentState.yaml currentState.workloads.<workload_name>`
7. The server has already stored this new state after the first try and does not instruct the runtime to deploy the workload.
8. The user does not receive any feedback about a reason that the workload was not deployed.

## Context (Environment)

Linux amd64
Podman

## Additional Information

We noticed this issue while developing a workload app managed by Ankaios, so a use case for not checking the workload states and waiting until the workload was really removed by the runtime is if you build and run the developed workload very often (like it is usual in a development cycle and if you are an impatient developer) and you forget to check the workload states between each test run of the developed workload.

The long deletion time of the runtime might be simulated through a workload that runs just a /bin/sleep 2000 as entrypoint and podman itself is running inside a container. So a container in container solution (like in devcontainers maybe). Here we noticed longer deletion times of workloads with the podman runtime.

## Final result

The current implementation was enhanced to support restarts/retries of failing create workloads. A failing create of a workload is restarted every 1 sec until the restart limit of 20 restarts is exceeded. Now, with this work the code base is also prepared internally to support general restarts of a workloads. This can be used and enhanced when restart policy functionality itself is developed in future releases.

**Comment by maturar** [comment]
I have tested the issue with current main (https://github.com/eclipse-ankaios/ankaios/commit/afbb44cf5b6c4c61d5e1462db47bf4e91b736f0e). It is the version with the pull request #100. **The bug is still there.** The difference is that the deletion in the step 2 (see the steps to reproduce) exits immediately. This is due to the change made in the PR #100. We use "fire and forget" in the CLI from now on. But the behavior is the same. I can see that the agent reports:
 ```
2023-11-23T14:37:35Z WARN  ank_agent::runtime_connectors::runtime_facade] Failed to create workload: 'infinity': 'Could not create workload: 'Execution of command failed: Error: creating container storage: the container name "infinity.bc86b38c3af658b7276ec555ab018e03cb46496fd15b77d6b6aed9e2469c1b7a.agent_A" is already in use by ddcd4aa95984595cca19b2ebda824a40e3dcf072014374cac061fc82b6230bdc. You have to remove that container to be able to reuse that name: that name is already in use
```
when we do quickly steps 2 and 3 (delete and set). The workload is in the state `removed` after the set and it remains in that state even if you try "update current state" again. If you want to recover from the situation, you have to delete the workload, wait long enough and then call update.

**Comment by maturar** [comment]
BTW: the "infinity" workload has been created from the image with this `Dockerfile`:

```
FROM alpine:latest
ENTRYPOINT ["tail", "-f", "/dev/null"]
```

**Comment by inf17101** [comment]
I have implemented a retry mechanism and tested it in this scenario and it fixes the problem. Now, I am checking if it fits to the architecture and if there are some side effects. I will discuss also with someone of the architects if I think it is ready.

**Comment by inf17101** [comment]
A restart mechanism is implemented to prevent such issues with runtime delays, see "Final Results" section inside the description for more details.
