### ISSUE TITLE
Convert a current state into a persistent startup state

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#68]
## Description

Currently, if you update the current state and you want that the workloads you have added/updated are also in the startup config as well, you need to copy the additional added workload configs to the startup state manually. This is because the initial state config is structured differently compared to the structure you receive when fetching the current state with the Ankaios CLI.

Of course you can use a suitable filter mask to reduce the incompatibility for example with `ank get state currentState.workloads` , but still you must do something manually to have a correct initial startup state config.

## Goals

Having a sub program on the Ankaios CLI for converting a current state into a startup state.

What would be nice to have would be that Ankaios CLI can generate a persistent initial startup state out of the current state:

`ank generate initial-state > new_initial_state.yaml` and `ank generate initial-state --out new_initial_state.yaml`

This can be the directly used when restarting the server:
`ank-server --startup-config new_initial_state.yaml`

### Summary

**To be filled when the final solution is sketched.**

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by krucod3** [comment]
We decided to remove the startup state from the config (will be done with #242), so this here is obsolete.
