### ISSUE TITLE
Setting GH Action job names for selfservice

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#70]
## Description

According to the examples provided in https://github.com/eclipse-ankaios/.eclipsefdn/pull/1 by Eclipse team members,
the examples are showing that mostly the GH Action job name is used inside the required status checks list. 

Currently we do not have job names set for each GH job and it is always good practice to have names.

This issue is in relation to #71 

## Goals

Introduce job names for our GH actions. Those shall be referenced in the selfservice configuration.

### Summary

Job names within all workflows were added and in addition a guideline for adding job names for new GH action jobs in the user documentation for ci cd was added.

### Tasks

- [x] Add job names to every job within all workflows
- [x] Extend user documentation through best practice about GH action job names

**Comment by netomi** [comment]
I dont think you have to use a job name, otherwise an implicit name will be used, but its certainly good practice.

**Comment by netomi** [comment]
I did check what would be the names of the status checks that are currently available:

![image](https://github.com/eclipse-ankaios/ankaios/assets/1048055/82420aa8-4c3c-45bc-9a76-caf00c86662e)

so you could just use these names when setting up a branch protection rule.

**Comment by netomi** [comment]
so the eclipsefdn/eca you dont have to setup as it comes by default.

**Comment by inf17101** [comment]
> I did check what would be the names of the status checks that are currently available:
> 
> ![image](https://user-images.githubusercontent.com/1048055/278574643-82420aa8-4c3c-45bc-9a76-caf00c86662e.png)
> 
> so you could just use these names when setting up a branch protection rule.

Yes that's true it picks the job id as default if no job name is defined. But I thought it is good practice to have job names in general.

**Comment by inf17101** [comment]
> I dont think you have to use a job name, otherwise an implicit job name will be used, but its certainly good practice.

Yes, thank you for that point. I have updated the issue description regarding that.
