### ISSUE TITLE
Add environment variable for Ankaios address

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#75]
## Description

Currently if the user changes the Ankaios server socket to another address and/or port the Ankaios user must provide the `--server-address http://<ip>:<port>` all the time when starting an agent and when using the Ankaios CLI. 
This is a bit redundant and can be simplified with adding the environment variable for the Ankaios server socket.

## Goals

Introduce an environment variable for setting the Ankaios Server socket address.

## Final result

When a user uses the Ankaios CLI, the user has now the possibility to set the ANK_SERVER_URL environment variable.

### Summary

Because of the clap issue that the wrong error context is output when an invalid value is set for the environment variable,
we decided to only create an env variable for the server url of the Ankaios CLI. We introduce env variables for the other Ankaios components later when the clap issue is resolved.
I am in discussion with the authors to develop a potential fix in the clap lib itself: https://github.com/clap-rs/clap/issues/5202

### Tasks

- [x] Implement env variable for Ankaios CLI named `ANK_SERVER_URL` that allows to set the server url
- [x] Create requirements

**Comment by inf17101** [comment]
The Ankaios agent and cli use the url (http://127.0.0.1:25551) and the Ankaios server uses the socket address only (127.0.0.1:25551). The question is if we prefer one environment variable and for the agent and the cli we append just the protocol prefix "http://" or we use two different env variables asuming that the three Ankaios components are rarely running on the same system so that it has a benefit to use one env variable.

If we use one env variable then there might be a change necessary if we introduce more protocols, then we can not easily append "http://". Maybe we can use protocol and socket address as two different settings. Then we are flexible if we add more protocols.

What do you think?

**Comment by windsource** [comment]
I think different environment variables for cli, agent and server might be better to have a clear relation between variable and tool but for the way to connect to the server a URL should be used that includes the scheme(protocol like http or https) and the other parts like domain etc.

**Comment by inf17101** [comment]
> I think different environment variables for cli, agent and server might be better to have a clear relation between variable and tool but for the way to connect to the server a URL should be used that includes the scheme (protocol like http or https) and the other parts like domain etc. The URL structure is pretty flexible (see https://en.m.wikipedia.org/wiki/URL) and various schemas have been defined.

I am not sure if three different environment variables have a real benefit. Ankaios CLI and Ankaios agent are using the URL format. So we can have an env variable for the URL format and the socket address for the server.

**Comment by inf17101** [comment]
Can I also make the support of the env variable in the requirements generic and link it in the clap argument structure in our code? For prioritizing the cli arg over the env var I have created a generalized requirement, but for the env variable I was not sure, because maybe some arguments in the future shall not be supported as env var and then I was not sure if it makes sense. What do you think?

**Comment by windsource** [comment]
> Make sense to me to also support this setup you have described. Then the better use-ability is with separate variables. @krucod3: We have first said that two env variables are enough. Is it also fine for you to introduce separate ones? We have also thought about only adding the env variable to the Ankaios CLI, not to agent and server because they are not started very often. This would reduce custom code until clap has fixed the issue. For now, a single "ANK_SERVER_URL" might be enough. Do you both agree with the naming of the key? Shall we add a system test for the env variable?

Fine for me. I am not sure if we need a system test for that.

**Comment by krucod3** [comment]
Maybe we should really go for 3 variables as proposed by @windsource. This way we can support the use-case where all 3 executables are running on the same machine, but you want to connect the CLI an/or the agent to a different server. It's a funny use-case, admittedly, but the variables would at least be mapped one-to-one with the input arguments

**Comment by inf17101** [comment]
> Maybe we should really go for 3 variables as proposed by @windsource. This way we can support the use-case where all 3 executables are running on the same machine, but you want to connect the CLI an/or the agent to a different server. It's a funny use-case, admittedly, but the variables would at least be mapped one-to-one with the input arguments

Yes I understand. The reason was that the Ankaios server and agent is not started very often, so the improvement is more on the side of the Ankaios CLI. But three variables are also fine for me. @windsource: Can I count your reaction on @krucod3 post as accepted for implementation?

**Comment by windsource** [comment]
So with 3 variables would mean:

- `ANK_SERVER_URL`
- `ANKAGENT_SERVER_URL`
- `ANKSERVER_ADDRESS`

Like that?

**Comment by inf17101** [comment]
Fine for me, I just thinking about the last one `ANKSERVER_ADDRESS`. I know that the current cli arg also is named `address` but should we include the "socket" also in the naming ? => `ANKSERVER_SOCKET_ADDRESS`

**Comment by windsource** [comment]
Fine for me.

**Comment by inf17101** [comment]
Ok then I will implement three variables with the accepted names above.

**Comment by inf17101** [comment]
As discussed with @krucod3: There are no stests added but claimed in the requirements. This will be done later, because of current other priorities.
