### ISSUE TITLE
Add more examples for Control Interface and make them consistent

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#77]
## Description

Currently, there is an example about how to use the Control Interface written in Rust.

But it might be helpful for development if more examples in various languages are added.

## Goals

Have more examples in more languages about the usage of the Control Interface.

For example:
- NodeJS
- Cpp
- Python

### Summary

**To be filled when the final solution is sketched.**

### Tasks

* Add control interface examples in different langauges.

**Comment by krucod3** [comment]
All done here.
