### ISSUE TITLE
Support Podman network mode

### ISSUE THREAD

**Issue by windsource** [eclipse-ankaios/ankaios#8]
## Description

Currently containers started with the Podman runtime use Podman's default network. We should support a runtime config option to set the network for the Podman runtime to use modes like `host`or `none`. This shall be done by passing the arguments one-to-one to Podman.

## Goals

- Containers share a common network which has been setup before (typically by the OEM in the automtive context).

## Tasks

- [x] Extend the config and Podman runtime adapter - #51

**Comment by maturar** [comment]
**How to set the network mode**
Unfortunately the documentation of the podman REST API does not say much about the network mode. There is another Rust crate which implements the Podman API. There I found an example how to set the network mode:
https://docs.rs/podtender/latest/podtender/index.html

I have combined the example with the library we use:
https://docs.rs/podman-api/latest/podman_api/opts/struct.ContainerCreateOptsBuilder.html#method.net_namespace

This implementation seems to work. See testing below.

**Comment by maturar** [comment]
**Testing the network mode**
The good image for the testing is the "unprivileged nginx". The image runs on the port 8080 (so you can run the server in the host network without any problems). The source page is here: 
https://www.tutorialworks.com/podman-host-networking/

My testing procedure was following. First I ran the nginx-unprivileged in the default (bridged) network mode. This works only with the port mapping:

```
    runtimeConfig: |
      image: nginxinc/nginx-unprivileged
      ports:
      - containerPort: 8080
        hostPort: 8080
```
You have to see a web page on the ```localhost:8080``` if the Ankaios creates and starts the container successfully. 

Then I tried to run the server in the host network. In this network mode you do not need port mapping:

```
    runtimeConfig: |
      image: nginxinc/nginx-unprivileged
      networkMode: host
```
If you set the network mode to ```none```, the browser fails to display the page.

**Comment by maturar** [comment]
The pull request has been reviewed and merged to the main.
