### ISSUE TITLE
Obsolete command for test coverage report generation in user documentation

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#82]
For generating the test coverage report a script was introduced that uses nextest already to execute the unit tests.
But on the documentation of the main branch there is still the obsolete command (cov test ...) mentioned.

See here: https://eclipse-ankaios.github.io/ankaios/main/development/test-coverage/

## Current Behavior

Obsolete command in the user documentation for executing the test coverage report.

## Expected Behavior

In the user documentation there shall be the script mentioned that shall be used to generate the test coverage report: `tools/generate_test_coverage_report`.

## Steps to Reproduce

Check the main branch documentation mentioned above.

## Final result

**To be filled by the one closing the issue.**

**Comment by krucod3** [comment]
cov is an alias to the above mentioned script. The command and the documentation are up to date. See the following link for more details: https://github.com/eclipse-ankaios/ankaios/blob/main/.devcontainer/Dockerfile#L26
